CondominioFacilDDD.MVC/ViewModels/ResidenciaViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CondominioFacilDDD.MVC.ViewModels
{
    public class ResidenciaViewModel
    {
        [Key]
        public int ResidenciaId { get; set; }

        [Required(ErrorMessage = "Preencha o campo numero")]
        [Range(1, Int16.MaxValue, ErrorMessage = "O numero deve ser maior que 1")]
        [DisplayName("Numero da Residência")]
        public string NResidencia { get; set; }

        [DisplayName("Nome da Rua")]
        public int RuaId { get; set; }

        public virtual RuaViewModel Rua { get; set; }
    }
}

CondominioFacilDDD.MVC/Controllers/ResidenciasController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using CondominioFacilDDD.Application.Interface;
using CondominioFacilDDD.Domain.Entities;
using CondominioFacilDDD.MVC.ViewModels;

namespace CondominioFacilDDD.MVC.Controllers
{
    public class ResidenciasController : Controller
    {
        private readonly IResidenciaAppService _residenciaApp;
        private readonly IRuaAppService _ruaApp;

        public ResidenciasController(IResidenciaAppService residenciaApp, IRuaAppService ruaApp)
        {
            _ruaApp = ruaApp;
            _residenciaApp = residenciaApp;
        }


       
        public ActionResult Index()
        {
            return View();
        }

        // GET: Residencias
        public ActionResult ListarResidencias()
        {
            var residenciaViewModel =
                Mapper.Map<IEnumerable<Residencia>, IEnumerable<ResidenciaViewModel>>(_residenciaApp.GetAll());
            return View(residenciaViewModel);
        }

        // GET: Residencias/Details/5
        public ActionResult Details(int id)
        {
            var residencia = _residenciaApp.GetById(id);
            var residenciaViewModel = Mapper.Map<Residencia, ResidenciaViewModel>(residencia);
            return View(residenciaViewModel);
            
        }

        // GET: Residencias/Create
        public ActionResult Create()
        {
            ViewBag.RuaId = new SelectList(_ruaApp.GetAll(), "RuaId", "Nome");
            return View();
        }

        // POST: Residencias/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ResidenciaViewModel residencia)
        {
            if (ModelState.IsValid)
            {
                var residenciaDomain = Mapper.Map<ResidenciaViewModel, Residencia>(residencia);
                _residenciaApp.Add(residenciaDomain);

                return RedirectToAction("Index");
            }
            ViewBag.RuaId = new SelectList(_ruaApp.GetAll(), "RuaId", "Nome", residencia.RuaId);
            return View(residencia);
        }

        // GET: Residencias/Edit/5
        public ActionResult Edit(int id)
        {
            var residencia = _residenciaApp.GetById(id);
            var residenciaViewModel = Mapper.Map<Residencia, ResidenciaViewModel>(residencia);

            ViewBag.RuaId = new SelectList(_ruaApp.GetAll(), "RuaId", "Nome", residenciaViewModel.RuaId);

            return View(residenciaViewModel);
        }

        // POST: Residencias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ResidenciaViewModel residencia)
        {
            if (ModelState.IsValid)
            {
                var residenciaDomain = Mapper.Map<ResidenciaViewModel, Residencia>(residencia);
                _residenciaApp.Update(residenciaDomain);
                return RedirectToAction("Index");
            }

            ViewBag.RuaId = new SelectList(_ruaApp.GetAll(), "RuaId", "Nome", residencia.RuaId);
            return View(residencia);
        }

        // GET: Residencias/Delete/5
        public ActionResult Delete(int id)
        {
            var residencia = _residenciaApp.GetById(id);
            var residenciaViewModel = Mapper.Map<Residencia, ResidenciaViewModel>(residencia);

            return View(residenciaViewModel);
        }

        // POST: Residencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var residencia = _residenciaApp.GetById(id);
            _residenciaApp.Remove(residencia);

            return RedirectToAction("Index");
        }
    }
}

CondominioFacilDDD.MVC/Views/Residencias/Create.cshtml
@model CondominioFacilDDD.MVC.ViewModels.ResidenciaViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Residência", "Index", "Residencias")
    </li>
    <li class="active">
        Cadastro
    </li>
</ul>
@{
    ViewBag.Title = "Cadastro de Residência";
}
<blockquote><h2>Cadastro de Residência</h2></blockquote>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RuaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RuaId", String.Empty)
                @Html.ValidationMessageFor(model => model.RuaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NResidencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NResidencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NResidencia, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Residências", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Residencias/Delete.cshtml
@model CondominioFacilDDD.MVC.ViewModels.ResidenciaViewModel

<ul class="breadcrumb">
    <span>VOCÊ ESTA EM:</span>
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Residência", "Index", "Residencias")
    </li>
    <li class="active">
        Excluir
    </li>
</ul>
@{
    ViewBag.Title = "Excluir Residência";
}
<blockquote><h2>Excluir Residência</h2></blockquote>


<h3>Tem certeza de que deseja excluir esta residência</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayName("Nome de Rua")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rua.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NResidencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NResidencia)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Voltar para residências", "Index")
            <input type="submit" value="Excluir" class="btn btn-default" /> 
            
        </div>
    }
</div>

CondominioFacilDDD.MVC/Views/Residencias/Details.cshtml
@model CondominioFacilDDD.MVC.ViewModels.ResidenciaViewModel

<ul class="breadcrumb">
    <span>VOCÊ ESTA EM:</span>
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Residência", "Index", "Residencias")
    </li>
    <li class="active">
        Detalhes
    </li>
</ul>
@{
    ViewBag.Title = "Detalhes da Residência";
}
<blockquote><h2>Detalhes da Residência</h2></blockquote>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayName("Nome da Rua")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rua.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NResidencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NResidencia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.ResidenciaId }) |
    @Html.ActionLink("Voltar para residências", "Index")
</p>

CondominioFacilDDD.MVC/Views/Residencias/Edit.cshtml
@model CondominioFacilDDD.MVC.ViewModels.ResidenciaViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Residência", "Index", "Residencias")
    </li>
    <li class="active">
        Atualizar
    </li>
</ul>
@{
    ViewBag.Title = "Atualizar Residência";
}
<blockquote><h2>Atualizar Residência</h2></blockquote>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ResidenciaId)

        <div class="form-group">
            @Html.LabelFor(model => model.RuaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RuaId", String.Empty)
                @Html.ValidationMessageFor(model => model.RuaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NResidencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NResidencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NResidencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para residências", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Residencias/Index.cshtml
@using System.Web.UI.WebControls
@model CondominioFacilDDD.MVC.ViewModels.RuaViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li class="active">
        Residências
    </li>
</ul>
@{
    ViewBag.Title = "Index";
}

<blockquote><h2>Residências</h2></blockquote>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Cadastro</h2>
            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Create", "Residencias")'">Nova residência</button>
        </div>
        <div class="col-md-4">
            <h2>Listar Residência</h2>

            @using (Html.BeginForm("ListarResidencias", "Residencias"))
            {
                <p><button type=submit class="btn btn-default">Listar todas residências</button></p>
            }

        </div>

       
    </div>
</div>

CondominioFacilDDD.MVC/Views/Residencias/ListarResidencias.cshtml
@model IEnumerable<CondominioFacilDDD.MVC.ViewModels.ResidenciaViewModel>

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Residência", "Index", "Residencias")
    </li>
    <li class="active">
        Lista
    </li>
</ul>
@{
    ViewBag.Title = "Lista de Residências";
}
<blockquote><h2>Lista de Residências</h2></blockquote>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nome da Rua")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NResidencia)

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Rua.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NResidencia)
            </td>
            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id = item.ResidenciaId }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.ResidenciaId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.ResidenciaId })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Voltar para Residências", "Index")
</div>