CondominioFacilDDD.MVC/ViewModels/CondominioViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CondominioFacilDDD.MVC.ViewModels
{
    public class CondominioViewModel
    {
        [Key]
        public int CondominioId { get; set; }

        [DisplayName("Numero da Residência")]
        public int ResidenciaId { get; set; }

        [DisplayName("Nome do Propietário")]
        public int PropietarioId { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCadastro { get; set; }

        public virtual ResidenciaViewModel Residencia { get; set; }

        public PropietarioViewModel Propietario { get; set; }
    }
}

CondominioFacilDDD.MVC/Controllers/CondominiosController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using CondominioFacilDDD.Application.Interface;
using CondominioFacilDDD.Domain.Entities;
using CondominioFacilDDD.MVC.ViewModels;

namespace CondominioFacilDDD.MVC.Controllers
{
    public class CondominiosController : Controller
    {
        private readonly ICondominioAppService _condominioApp;
        private readonly IPropietarioAppService _propietarioApp;
        private readonly IResidenciaAppService _residenciaApp;

        public CondominiosController(ICondominioAppService condominioApp, IPropietarioAppService propietarioApp, IResidenciaAppService residenciaApp)
        {
            _condominioApp = condominioApp;
            _propietarioApp = propietarioApp;
            _residenciaApp = residenciaApp;
        }

        // GET: Condominios
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListarCondominios()
        {
            var condominioViewModel = Mapper.Map<IEnumerable<Condominio>, IEnumerable<CondominioViewModel>>(_condominioApp.GetAll());
            return View(condominioViewModel);
        }

        // GET: Condominios/Details/5
        public ActionResult Details(int id)
        {
            var condominio = _condominioApp.GetById(id);
            var condominioViewModel = Mapper.Map<Condominio, CondominioViewModel>(condominio);
            return View(condominioViewModel);
        }

        // GET: Condominios/Create
        public ActionResult Create()
        {
            ViewBag.ResidenciaId = new SelectList(_residenciaApp.GetAll(), "ResidenciaId", "NResidencia");
            ViewBag.PropietarioId = new SelectList(_propietarioApp.GetAll(), "PropietarioId", "Nome");
            return View();
        }

        // POST: Condominios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CondominioViewModel condominio)
        {

            if (ModelState.IsValid)
            {
                var condominioDomain = Mapper.Map<CondominioViewModel, Condominio>(condominio);
                _condominioApp.Add(condominioDomain);

                return RedirectToAction("Index");
            }

            ViewBag.ResidenciaId = new SelectList(_residenciaApp.GetAll(), "ResidenciaId", "NResidencia", condominio.ResidenciaId);
            ViewBag.PropietarioId = new SelectList(_propietarioApp.GetAll(), "PropietarioId", "Nome", condominio.PropietarioId);
            return View(condominio);
        }

        // GET: Condominios/Edit/5
        public ActionResult Edit(int id)
        {
            var condominio = _condominioApp.GetById(id);
            var condominioViewModel = Mapper.Map<Condominio, CondominioViewModel>(condominio);

            ViewBag.ResidenciaId = new SelectList(_residenciaApp.GetAll(), "ResidenciaId", "NResidencia");
            ViewBag.PropietarioId = new SelectList(_propietarioApp.GetAll(), "PropietarioId", "Nome");

            return View(condominioViewModel);
        }

        // POST: Condominios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CondominioViewModel condominio)
        {
            if (ModelState.IsValid)
            {
                var condominioDomain = Mapper.Map<CondominioViewModel, Condominio>(condominio);
                _condominioApp.Update(condominioDomain);
                return RedirectToAction("Index");
            }
            ViewBag.ResidenciaId = new SelectList(_residenciaApp.GetAll(), "ResidenciaId", "NResidencia", condominio.ResidenciaId);
            ViewBag.PropietarioId = new SelectList(_propietarioApp.GetAll(), "PropietarioId", "Nome", condominio.PropietarioId);
            return View(condominio);
        }

        // GET: Condominios/Delete/5
        public ActionResult Delete(int id)
        {
            var condominio = _condominioApp.GetById(id);
            var condominioViewModel = Mapper.Map<Condominio, CondominioViewModel>(condominio);

            return View(condominioViewModel);
        }

        // POST: Condominios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var condominio = _condominioApp.GetById(id);
            _condominioApp.Remove(condominio);

            return RedirectToAction("Index");
        }
    }
}

CondominioFacilDDD.MVC/Views/Condominios/Create.cshtml
@model CondominioFacilDDD.MVC.ViewModels.CondominioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Condominio", "Index", "Condominios")
    </li>
    <li class="active">
        Cadastro
    </li>
</ul>
@{
    ViewBag.Title = "Cadastro de Condominios";
}
<blockquote><h2>Cadastro de Condominios</h2></blockquote>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ResidenciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResidenciaId", String.Empty)
                @Html.ValidationMessageFor(model => model.ResidenciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropietarioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PropietarioId", String.Empty)
                @Html.ValidationMessageFor(model => model.PropietarioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Condominios", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Condominios/Delete.cshtml
@model CondominioFacilDDD.MVC.ViewModels.CondominioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Condominio", "Index", "Condominios")
    </li>
    <li class="active">
        Cadastro
    </li>
</ul>
@{
    ViewBag.Title = "Excluir Condominios";
}
<blockquote><h2>Exclusão de Condominios</h2></blockquote>
<h3>Tem certeza de que deseja excluir este condominio?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PropietarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Propietario.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResidenciaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResidenciaId)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para condominios", "Index")
        </div>
    }
</div>

CondominioFacilDDD.MVC/Views/Condominios/Details.cshtml
@model CondominioFacilDDD.MVC.ViewModels.CondominioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Condominio", "Index", "Condominios")
    </li>
    <li class="active">
        Detalhes
    </li>
</ul>
@{
    ViewBag.Title = "Detalhes dos Condominios";
}
<blockquote><h2>Detalhes dos Condominios</h2></blockquote>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PropietarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Propietario.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResidenciaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Residencia.NResidencia)
        </dd>

      

    </dl>
</div>
<p>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.CondominioId }) |
    @Html.ActionLink("Voltar para Condominios", "Index")
</p>

CondominioFacilDDD.MVC/Views/Condominios/Edit.cshtml
@model CondominioFacilDDD.MVC.ViewModels.CondominioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Condominio", "Index", "Condominios")
    </li>
    <li class="active">
        Atualizar
    </li>
</ul>
@{
    ViewBag.Title = "Atualizar Condomínio";
}
<blockquote><h2>Atualizar Condomínio</h2></blockquote>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CondominioId)

        <div class="form-group">
            @Html.LabelFor(model => model.ResidenciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResidenciaId", String.Empty)
                @Html.ValidationMessageFor(model => model.ResidenciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropietarioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PropietarioId", String.Empty)
                @Html.ValidationMessageFor(model => model.PropietarioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Condominios", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Condominios/Index.cshtml
@model CondominioFacilDDD.MVC.ViewModels.CondominioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li class="active">
        Condominios
    </li>
</ul>
@{
    ViewBag.Title = "Index";
}

<blockquote><h2>Condomínios</h2></blockquote>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Cadastro</h2>
            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Create", "Condominios")'">Novo Condomínio</button>
        </div>


        <div class="col-md-4">
            <h2>Listar Condomínios</h2>

            @using (Html.BeginForm("ListarCondominios", "Condominios"))
            {
                <p><button type=submit class="btn btn-default">Listar todos Condomínios</button></p>
            }

        </div>


    </div>
</div>

CondominioFacilDDD.MVC/Views/Condominios/ListarCondominios.cshtml
@model IEnumerable<CondominioFacilDDD.MVC.ViewModels.CondominioViewModel>

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Condomínios", "Index", "Condominios")
    </li>
    <li class="active">
        Lista
    </li>
</ul>
@{
    ViewBag.Title = "Lista de Condomínios";
}
<blockquote><h2>Lista de Condomínios</h2></blockquote>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nome do Propietário")
        </th>
        <th>
            @Html.DisplayName("Numero da Residência")
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Propietario.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Residencia.NResidencia )
        </td>
        
        <td>
            @Html.ActionLink("Atualizar", "Edit", new { id=item.CondominioId }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.CondominioId }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.CondominioId })
        </td>
    </tr>
}

</table>