CondominioFacilDDD.MVC/ViewModels/PropietarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CondominioFacilDDD.MVC.ViewModels
{
    public class PropietarioViewModel
    {
        [Key]
        public int PropietarioId { get; set; }

        [Required(ErrorMessage = "Preencha o campo nome")]
        [MaxLength(150, ErrorMessage = "Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage = "Mínimo {0} caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Preencha o campo sobrenome")]
        [MaxLength(150, ErrorMessage = "Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage = "Mínimo {0} caracteres")]
        [DisplayName("Sobre Nome")]
        public string SobreNome { get; set; }

        [Required(ErrorMessage = "Preencha o campo E-mail")]
        [MaxLength(100, ErrorMessage = "Máximo {0} caracteres")]
        [EmailAddress(ErrorMessage = "Preencha um E-mail válido")]
        [DisplayName("E-Mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Preencha o campo Telefone")]
        [MaxLength(100, ErrorMessage = "Máximo {0} caracteres")]
        [RegularExpression(@"^\d{4}[-]{1}\d{4}$", ErrorMessage = "Telefone inválido. Informe ####-####.")]
        public string Telefone { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCadastro { get; set; }
        public bool Ativo { get; set; }

        public virtual IEnumerable<CondominioViewModel> Condominios { get; set; }
    }
}

CondominioFacilDDD.MVC/Controllers/PropietariosController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using CondominioFacilDDD.Application.Interface;
using CondominioFacilDDD.Domain.Entities;
using CondominioFacilDDD.MVC.ViewModels;

namespace CondominioFacilDDD.MVC.Controllers
{
    public class PropietariosController : Controller
    {
        private readonly IPropietarioAppService _propietarioApp;

        public PropietariosController(IPropietarioAppService propietarioApp)
        {
            _propietarioApp = propietarioApp;
        }

        // GET: Propietarios
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListarPropietarios()
        {
            var propietarioViewModel = Mapper.Map<IEnumerable<Propietario>, IEnumerable<PropietarioViewModel>>(_propietarioApp.GetAll());
            return View(propietarioViewModel);
        }

        [HttpPost]
        public ActionResult BuscarNome(string nome)
        {
            var propietarioViewModel = Mapper.Map<IEnumerable<Propietario>, IEnumerable<PropietarioViewModel>>(_propietarioApp.BuscarPorNome(nome));
            return View(propietarioViewModel);
        }

        public ActionResult Especiais()
        {
            var propietarioViewModel =
                Mapper.Map<IEnumerable<Propietario>, IEnumerable<PropietarioViewModel>>(_propietarioApp.ObterPropietariosEspeciais());

            return View(propietarioViewModel);
        }

        // GET: Propietarios/Details/5
        public ActionResult Details(int id)
        {
            var propietario = _propietarioApp.GetById(id);
            var propietarioViewModel = Mapper.Map<Propietario, PropietarioViewModel>(propietario);
            return View(propietarioViewModel);
        }

        // GET: Propietarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Propietarios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PropietarioViewModel propietario)
        {
            if (ModelState.IsValid)
            {
                var propietarioDomain = Mapper.Map<PropietarioViewModel, Propietario>(propietario);
                _propietarioApp.Add(propietarioDomain);

                return RedirectToAction("Index");
            }
            return View(propietario);
        }

        // GET: Propietarios/Edit/5
        public ActionResult Edit(int id)
        {
            var propietario = _propietarioApp.GetById(id);
            var propietarioViewModel = Mapper.Map<Propietario, PropietarioViewModel>(propietario);

            return View(propietarioViewModel);
        }

        // POST: Propietarios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PropietarioViewModel propietario)
        {
            if (ModelState.IsValid)
            {
                var propietarioDomain = Mapper.Map<PropietarioViewModel, Propietario>(propietario);
                _propietarioApp.Update(propietarioDomain);
                return RedirectToAction("Index");
            }
            return View(propietario);
        }


        // GET: Propietarios/Delete/5
        public ActionResult Delete(int id)
        {
            var propietario = _propietarioApp.GetById(id);
            var propietarioViewModel = Mapper.Map<Propietario, PropietarioViewModel>(propietario);

            return View(propietarioViewModel);
        }

        // POST: Propietarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var propietario = _propietarioApp.GetById(id);
            _propietarioApp.Remove(propietario);
            return RedirectToAction("Index");
        }
    }
}

CondominioFacilDDD.MVC/Views/Propietarios/BuscarNome.cshtml
@model IEnumerable<CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel>
<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Buscar por Nome
    </li>
</ul>

@{
    ViewBag.Title = "Buscar por Nome";
}


<blockquote><h2>Busca de propietários</h2></blockquote>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SobreNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id = item.PropietarioId }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.PropietarioId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.PropietarioId })
            </td>
        </tr>
    }

</table>

CondominioFacilDDD.MVC/Views/Propietarios/Create.cshtml
@model CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel

<ul class="breadcrumb">
    <span>VOCÊ ESTA EM:</span>
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios") 
    </li>
    <li class="active">
        Cadastro
    </li>
</ul>
@{
    ViewBag.Title = "Cadastro de Propietário";
}
<blockquote><h2>Cadastro de Propietário</h2></blockquote>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SobreNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SobreNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SobreNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para propietários", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Propietarios/Delete.cshtml
@model CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Excluir
    </li>
</ul>

@{
    ViewBag.Title = "Excluir";
}

<blockquote><h2>Detalhes do propietário</h2></blockquote>

<h3>Tem certeza de que deseja excluir este propietário(a)?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SobreNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Voltar para Propietários", "Index")
            <input type="submit" value="Excluir" class="btn btn-default" /> |
        </div>
    }
</div>

CondominioFacilDDD.MVC/Views/Propietarios/Details.cshtml
@model CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel
<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Detalhes
    </li>
</ul>
@{
    ViewBag.Title = "Detalhes do Propietários";
}

<blockquote><h2>Detalhes do propietário</h2></blockquote>

<div>
    <h4>Propietario(a)  @Html.DisplayFor(model => model.Nome) @Html.DisplayFor(model => model.SobreNome)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SobreNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.PropietarioId }) |
    @Html.ActionLink("Voltar para Propietários", "Index")
</p>

CondominioFacilDDD.MVC/Views/Propietarios/Edit.cshtml
@model CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel
<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Atualizar
    </li>
</ul>
@{
    ViewBag.Title = "Atualizar Propietário";
}

<blockquote><h2>Atualizar Propietário</h2></blockquote>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PropietarioId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SobreNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SobreNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SobreNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Propietários", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CondominioFacilDDD.MVC/Views/Propietarios/Especiais.cshtml
@model IEnumerable<CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel>


<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Propietários Especiais
    </li>
</ul>
@{
    ViewBag.Title = "Especiais";
}

<blockquote><h2>Propietários Especiais</h2></blockquote>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SobreNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SobreNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ativo)
        </td>
        <td>
            @Html.ActionLink("Atualizar", "Edit", new { id=item.PropietarioId }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.PropietarioId }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.PropietarioId })
        </td>
    </tr>
}

</table>

CondominioFacilDDD.MVC/Views/Propietarios/Index.cshtml
@using System.Web.UI.WebControls
@model CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel

<ul class="breadcrumb">
    VOCÊ ESTA EM: 
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li class="active">
        Propietários
    </li>
</ul>
@{
    ViewBag.Title = "Index";
}

<blockquote><h2>Propietários</h2></blockquote>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Cadastro</h2>
            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Create", "Propietarios")'">Novo propietário</button>
        </div>
        <div class="col-md-4">
            <h2>Listar Propietários</h2>
           
            @using (Html.BeginForm("ListarPropietarios", "Propietarios"))
            {
                <p><button type=submit class="btn btn-default">Listar todos propietários</button></p>
            }
            
            @using (Html.BeginForm("Especiais", "Propietarios"))
            {
                <hr />
                <p><button type=submit class="btn btn-default">Listar propietários especiais</button></p>
            }
        </div>

        <div class="col-md-4">
            <h2>Buscar propietários</h2>
            
                @using (Html.BeginForm("BuscarNome", "Propietarios"))
                {
                    @Html.TextBoxFor(model => model.Nome, new {PlaceHolder="Digite um nome" })
                   
                    <hr/>
                    <p><button type="submit" class="btn btn-default">Buscar</button></p>
                }
            
                
            
                


    </div>
    </div>
</div>

CondominioFacilDDD.MVC/Views/Propietarios/ListarPropietarios.cshtml
@model IEnumerable<CondominioFacilDDD.MVC.ViewModels.PropietarioViewModel>

<ul class="breadcrumb">
    VOCÊ ESTA EM:
    <li>
        @Html.ActionLink("Home", "Index", "Home")
    </li>
    <li>
        @Html.ActionLink("Propietários", "Index", "Propietarios")
    </li>
    <li class="active">
        Lista
    </li>
</ul>

@{
    ViewBag.Title = "Listar Propietários";
}

<blockquote><h2>Lista de propietários</h2></blockquote>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SobreNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id = item.PropietarioId }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.PropietarioId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.PropietarioId })
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Voltar para propietários", "Index")
</div>